In [2]:
pip install -U fortran-magic

In [3]:
%matplotlib inline
%load_ext fortranmagic

import sys; sys.path.append('..')

import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

mpl.rc('figure', figsize=(12, 7))

ran_the_first_cell = True

jan2017 = pd.to_datetime(['2017-01-03 00:00:00+00:00',
 '2017-01-04 00:00:00+00:00',
 '2017-01-05 00:00:00+00:00',
 '2017-01-06 00:00:00+00:00',
 '2017-01-09 00:00:00+00:00',
 '2017-01-10 00:00:00+00:00',
 '2017-01-11 00:00:00+00:00',
 '2017-01-12 00:00:00+00:00',
 '2017-01-13 00:00:00+00:00',
 '2017-01-17 00:00:00+00:00',
 '2017-01-18 00:00:00+00:00',
 '2017-01-19 00:00:00+00:00',
 '2017-01-20 00:00:00+00:00',
 '2017-01-23 00:00:00+00:00',
 '2017-01-24 00:00:00+00:00',
 '2017-01-25 00:00:00+00:00',
 '2017-01-26 00:00:00+00:00',
 '2017-01-27 00:00:00+00:00',
 '2017-01-30 00:00:00+00:00',
 '2017-01-31 00:00:00+00:00',
 '2017-02-01 00:00:00+00:00'])
calendar = jan2017.values.astype('datetime64[D]')

event_dates = pd.to_datetime(['2017-01-06 00:00:00+00:00', 
                             '2017-01-07 00:00:00+00:00', 
                             '2017-01-08 00:00:00+00:00']).values.astype('datetime64[D]')
event_values = np.array([10, 15, 20])

/usr/local/lib/python3.7/dist-packages/fortranmagic.py:147: UserWarning: get_ipython_cache_dir has moved to the IPython.paths module since IPython 4.0.
  self._lib_dir = os.path.join(get_ipython_cache_dir(), 'fortran')


Pablo Cristancho (Twitter: @scottbsanderson, GitHub: ssanderson)
https://github.com/ssanderson/pydata-toolbox

> Bloque con sangría


About Me:

About Me:

Drawing

Senior Engineer at Quantopian

Background in Mathematics and Philosophy

Twitter: @scottbsanderson
GitHub: ssanderson

# Outline
Built-in Data Structures

Numpy array
Pandas Series/DataFrame
Plotting and "Real-World" Analyses

# Data Structures
Rule 5. Data dominates. If you've chosen the right data structures and organized things well, the algorithms will almost always be self-evident. Data structures, not algorithms, are central to programming.

Notes on Programming in C, by Rob Pike.

In [4]:
assert ran_the_first_cell, "Oh noes!"

In [5]:
#Ejemplo 1:

x = [123, 'Balon', 3.1415, 4.245, 1238, "pero"]
x

[123, 'Balon', 3.1415, 4.245, 1238, 'pero']

In [7]:
#Ejemplo 2:
primero = x[0]
segundo = x[1]
print("primero:", primero)
print("segundo:", segundo)

primero: 123
segundo: Balon


In [12]:
# Lists can be indexed like C-style arrays.
primero = x[0]
segundo = x[1]
print("primero:", primero)
print("segundo:", segundo)

primero: 123
segundo: Balon


# Review: Python Lists
Zero-indexed sequence of arbitrary Python values.
Slicing syntax: l[start:stop:step] copies elements at regular intervals from start to stop.
Efficient (O(1)) appends and removes from end.
Comprehension syntax: [f(x) for x in l if cond(x)].

In [15]:
#Ejemplo 3:

Futbolistas = {'Ospina': 'Cuadrado', 'Falcao': 'Ronaldinho', 'El': 'Bicho'}
Futbolistas

{'El': 'Bicho', 'Falcao': 'Ronaldinho', 'Ospina': 'Cuadrado'}

In [16]:
Futbolistas['Falcao'] = 'Falcao'
Futbolistas

{'El': 'Bicho', 'Falcao': 'Falcao', 'Ospina': 'Cuadrado'}

In [19]:
del Futbolistas['Falcao']
Futbolistas

{'El': 'Bicho', 'Ospina': 'Cuadrado'}

# Review: Python Dictionaries
Unordered key-value mapping from (almost) arbitrary keys to arbitrary values.
Efficient (O(1)) lookup, insertion, and deletion.
No slicing (would require a notion of order).

In [37]:
#ejemplo 4:

a = [[1, 2, 3],
     [2, 3, 4],
     [5, 6, 7],
     [1, 1, 1]]

b = [[1, 2, 3, 4],
     [2, 3, 4, 5]]

In [32]:
matriz1 = [[2, 9, 1, 7],
            [13, 5, 11, 3],
            [6, 1, 7, 22],
            [4, 5, 9, 6]]

matriz2 = [[2, 5, 9],
             [10, 9, 4],
             [5, 31, 3],
             [25, 2, 21]]

In [38]:
def matmul(A, B):
    """Multiply matrix A by matrix B."""
    rows_out = len(A)
    cols_out = len(B[0])
    out = [[0 for col in range(cols_out)] for row in range(rows_out)]
    
    for i in range(rows_out):
        for j in range(cols_out):
            for k in range(len(B)):
                out[i][j] += A[i][k] * B[k][j]
    return out

In [40]:
%%time

matmul(a, b)

CPU times: user 35 µs, sys: 5 µs, total: 40 µs
Wall time: 44.3 µs


[[5, 8, 11, 14], [8, 13, 18, 23], [17, 28, 39, 50], [3, 5, 7, 9]]

In [42]:
%%time
matmul(matriz1, matriz2)

CPU times: user 41 µs, sys: 7 µs, total: 48 µs
Wall time: 53.2 µs


[[274, 136, 204], [206, 457, 233], [607, 300, 541], [253, 356, 209]]

# Why is the Python Version so Slow?
Dynamic typing means that every single operation requires dispatching on the input type.
Having an interpreter means that every instruction is fetched and dispatched at runtime.
Other overheads:
Arbitrary-size integers.
Reference-counted garbage collection.
This is the paradox that we have to work with when we're doing scientific or numerically-intensive Python. What makes Python fast for development -- this high-level, interpreted, and dynamically-typed aspect of the language -- is exactly what makes it slow for code execution.

Jake VanderPlas, Losing Your Loops: Fast Numerical Computing with NumPy

# What Do We Do?

Python is slow for numerical computation because it performs dynamic dispatch on every operation we perform...
...but often, we just want to do the same thing over and over in a loop!
If we don't need Python's dynamicism, we don't want to pay (much) for it.
Idea: Dispatch once per operation instead of once per element.

In [55]:
list_dato = [float(i) for i in range(50000)]
array_data = np.array(list_dato)

In [48]:
#ejemplo 5:
dato = np.array([2, 4, 6, 8])
dato

array([2, 4, 6, 8])

In [47]:
import numpy as np

data = np.array([1, 2, 3, 4])
data

array([1, 2, 3, 4])

In [49]:
#ejemplo 6:
dato + dato

array([ 4,  8, 12, 16])

In [50]:
data + data

array([2, 4, 6, 8])

In [53]:
%%time
(array_dato * array_dato).sum()

CPU times: user 1.15 ms, sys: 18 µs, total: 1.17 ms
Wall time: 1.19 ms


41665416675000.0

In [56]:
%%time
# Naive dot product
(array_data * array_data).sum()

CPU times: user 254 µs, sys: 0 ns, total: 254 µs
Wall time: 263 µs


41665416675000.0

# What's in an Array?

In [57]:
arr = np.array([10, 20, 30, 40, 50, 60], dtype='int16').reshape(40, 50)
print("Array:\n", arr, sep='')
print("===========")
print("DType:", arr.dtype)
print("Shape:", arr.shape)
print("Strides:", arr.strides)
print("Data:", arr.data.tobytes())

ValueError: ignored